{{ if .Values.autoscaling }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "coolkit.deployment-name" . }}
  {{ .Values.autoscaling | toYaml | nindent 2 }}
{{ end }}
