apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}"
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels: {{ include "coolkit.match-labels" . | nindent 6 }}
